language: python
python: 2.7
env:
    - TOX_ENV=py26
    - TOX_ENV=py27
    - TOX_ENV=py32
    - TOX_ENV=py33
    - TOX_ENV=pypy
install:
- pip install tox
- pip install coveralls
script: tox -e $TOX_ENV
after_success: coveralls
deploy:
  provider: pypi
  user: luizirber
  password:
    secure: Fsxf0WWg2/dgG+lQxK7+rff8aFcLmpS0Fe44c/Kl7Aw1HiQl+x9ElRMpbNb+qZz7Rfc7m/8VG6lgsADEn8e9gcyZUjyDqzjrNJ3vK9K/7xWDCp6S7sjiHWfE3gm8QnOo2on6ZGUaGgeqppVXqGXhOrwTEx63EcU+jA6YlBUDYGo=
  on:
    tags: true
    repo: luizirber/rec_env
