language: python
python:
- '2.6'
- '2.7'
- '3.2'
- '3.3'
install:
- pip install -r requirements-dev.txt --use-mirrors
- pip install coverage
- pip install coveralls
script:
- python setup.py test
after_success: coveralls
deploy:
  provider: pypi
  user: luizirber
  password:
    secure: Fsxf0WWg2/dgG+lQxK7+rff8aFcLmpS0Fe44c/Kl7Aw1HiQl+x9ElRMpbNb+qZz7Rfc7m/8VG6lgsADEn8e9gcyZUjyDqzjrNJ3vK9K/7xWDCp6S7sjiHWfE3gm8QnOo2on6ZGUaGgeqppVXqGXhOrwTEx63EcU+jA6YlBUDYGo=
  on:
    tags: true
    repo: luizirber/rec_env
